use serde::Serialize;

// 结构化高级参数注册表：数据驱动，单一真源在 Rust（默认值 + 序列化规则均在此）。
// 前端通过 get_param_registry 命令拉取同一份元数据，通用渲染控件，无需为每个参数写硬编码 UI。
// 新增官方参数只需在此表加一行 + 在 src/i18n/messages.ts 补 advanced.structured.<key> 文案。

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum ParamType {
    Int,
    Float,
    Bool,
    Str,
    Enum,
}

// 全部字段用 &'static str / &'static [..]：使 PARAM_REGISTRY 能写成 const
// （const 上下文不允许 String / vec! 这类堆分配），同时零运行时开销。
#[derive(Debug, Clone, Copy, Serialize)]
pub struct ParamSpec {
    pub key: &'static str,
    pub flag: &'static str,
    #[serde(rename = "type")]
    pub ptype: ParamType,
    pub default: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub choices: Option<&'static [&'static str]>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub widget: Option<&'static str>,
    pub enabled_by_default: bool,
}

impl ParamSpec {
    /// 按注册表声明把「键 + 用户值」序列化成 llama-server 命令行片段。
    /// Bool 型只在真值时输出裸 flag；其余类型输出 `--flag value`，空值视为未设置。
    pub fn to_args(self, raw: &str) -> Vec<String> {
        let value = raw.trim();
        match self.ptype {
            ParamType::Bool => {
                if matches!(value, "true" | "1" | "on" | "yes") {
                    vec![self.flag.to_string()]
                } else {
                    Vec::new()
                }
            }
            _ => {
                if value.is_empty() {
                    Vec::new()
                } else {
                    vec![self.flag.to_string(), value.to_string()]
                }
            }
        }
    }
}

/// 按 key 查注册表声明；未知 key 返回 None（旧配置里的废弃参数将被安全忽略）。
pub fn find_spec(key: &str) -> Option<&'static ParamSpec> {
    PARAM_REGISTRY.iter().find(|spec| spec.key == key)
}

pub const PARAM_REGISTRY: &[ParamSpec] = &[
    ParamSpec {
        key: "threads_batch",
        flag: "--threads-batch",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "cpu_strict",
        flag: "--cpu-strict",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "prio",
        flag: "--prio",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "parallel",
        flag: "--parallel",
        ptype: ParamType::Int,
        default: "1",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "keep",
        flag: "--keep",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "swa_full",
        flag: "--swa-full",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "kv_offload",
        flag: "--kv-offload",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_kv_offload",
        flag: "--no-kv-offload",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "repack",
        flag: "--repack",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_repack",
        flag: "--no-repack",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "cache_type_k",
        flag: "--cache-type-k",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "cache_type_v",
        flag: "--cache-type-v",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "rope_scaling",
        flag: "--rope-scaling",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "rope_scale",
        flag: "--rope-scale",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "rope_freq_base",
        flag: "--rope-freq-base",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "rope_freq_scale",
        flag: "--rope-freq-scale",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "yarn_orig_ctx",
        flag: "--yarn-orig-ctx",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "yarn_ext_factor",
        flag: "--yarn-ext-factor",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "yarn_attn_factor",
        flag: "--yarn-attn-factor",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "yarn_beta_slow",
        flag: "--yarn-beta-slow",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "yarn_beta_fast",
        flag: "--yarn-beta-fast",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "mmproj",
        flag: "--mmproj",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: Some("file"),
        enabled_by_default: false,
    },
    ParamSpec {
        key: "mmproj_url",
        flag: "--mmproj-url",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "image_min_tokens",
        flag: "--image-min-tokens",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "image_max_tokens",
        flag: "--image-max-tokens",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "rpc",
        flag: "--rpc",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "numa",
        flag: "--numa",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "device",
        flag: "--device",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "override_tensor",
        flag: "--override-tensor",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "cpu_moe",
        flag: "--cpu-moe",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "n_cpu_moe",
        flag: "--n-cpu-moe",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "split_mode",
        flag: "--split-mode",
        ptype: ParamType::Enum,
        default: "none",
        min: None,
        max: None,
        choices: Some(&["none", "layer", "row"]),
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "tensor_split",
        flag: "--tensor-split",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "main_gpu",
        flag: "--main-gpu",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "fit",
        flag: "--fit",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "fit_target",
        flag: "--fit-target",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "fit_ctx",
        flag: "--fit-ctx",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "override_kv",
        flag: "--override-kv",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "op_offload",
        flag: "--op-offload",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_op_offload",
        flag: "--no-op-offload",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "log_disable",
        flag: "--log-disable",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "log_file",
        flag: "--log-file",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "log_colors",
        flag: "--log-colors",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "verbosity",
        flag: "--verbosity",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "log_prefix",
        flag: "--log-prefix",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_log_prefix",
        flag: "--no-log-prefix",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "log_timestamps",
        flag: "--log-timestamps",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_log_timestamps",
        flag: "--no-log-timestamps",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "control_vector",
        flag: "--control-vector",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "control_vector_scaled",
        flag: "--control-vector-scaled",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "control_vector_layer_range",
        flag: "--control-vector-layer-range",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "check_tensors",
        flag: "--check-tensors",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "samplers",
        flag: "--samplers",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "sampler_seq",
        flag: "--sampler-seq",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "seed",
        flag: "--seed",
        ptype: ParamType::Int,
        default: "-1",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "ignore_eos",
        flag: "--ignore-eos",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "top_k",
        flag: "--top-k",
        ptype: ParamType::Int,
        default: "40",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "top_p",
        flag: "--top-p",
        ptype: ParamType::Float,
        default: "0.95",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "min_p",
        flag: "--min-p",
        ptype: ParamType::Float,
        default: "0.05",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "top_nsigma",
        flag: "--top-nsigma",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "xtc_probability",
        flag: "--xtc-probability",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "xtc_threshold",
        flag: "--xtc-threshold",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "typical",
        flag: "--typical",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "repeat_last_n",
        flag: "--repeat-last-n",
        ptype: ParamType::Int,
        default: "64",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "repeat_penalty",
        flag: "--repeat-penalty",
        ptype: ParamType::Float,
        default: "1.1",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "presence_penalty",
        flag: "--presence-penalty",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "frequency_penalty",
        flag: "--frequency-penalty",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "dry_multiplier",
        flag: "--dry-multiplier",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "dry_base",
        flag: "--dry-base",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "dry_allowed_length",
        flag: "--dry-allowed-length",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "dry_penalty_last_n",
        flag: "--dry-penalty-last-n",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "dry_sequence_breaker",
        flag: "--dry-sequence-breaker",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "adaptive_target",
        flag: "--adaptive-target",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "adaptive_decay",
        flag: "--adaptive-decay",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "dynatemp_range",
        flag: "--dynatemp-range",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "dynatemp_exp",
        flag: "--dynatemp-exp",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "mirostat",
        flag: "--mirostat",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "mirostat_lr",
        flag: "--mirostat-lr",
        ptype: ParamType::Float,
        default: "0.1",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "mirostat_ent",
        flag: "--mirostat-ent",
        ptype: ParamType::Float,
        default: "5.0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "logit_bias",
        flag: "--logit-bias",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "grammar",
        flag: "--grammar",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "grammar_file",
        flag: "--grammar-file",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "json_schema",
        flag: "--json-schema",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "json_schema_file",
        flag: "--json-schema-file",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "backend_sampling",
        flag: "--backend-sampling",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "server_base",
        flag: "--server-base",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "lookup_cache_static",
        flag: "--lookup-cache-static",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "lookup_cache_dynamic",
        flag: "--lookup-cache-dynamic",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "ctx_checkpoints",
        flag: "--ctx-checkpoints",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "checkpoint_min_step",
        flag: "--checkpoint-min-step",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "cache_ram",
        flag: "--cache-ram",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "cache_idle_slots",
        flag: "--cache-idle-slots",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_cache_idle_slots",
        flag: "--no-cache-idle-slots",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "context_shift",
        flag: "--context-shift",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_context_shift",
        flag: "--no-context-shift",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "pooling",
        flag: "--pooling",
        ptype: ParamType::Enum,
        default: "none",
        min: None,
        max: None,
        choices: Some(&["none", "mean", "cls"]),
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "attention",
        flag: "--attention",
        ptype: ParamType::Enum,
        default: "none",
        min: None,
        max: None,
        choices: Some(&["none", "sdqa"]),
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "warmup",
        flag: "--warmup",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_warmup",
        flag: "--no-warmup",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "reverse_prompt",
        flag: "--reverse-prompt",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "special",
        flag: "--special",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "spm_infill",
        flag: "--spm-infill",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "cont_batching",
        flag: "--cont-batching",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_cont_batching",
        flag: "--no-cont-batching",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "lora",
        flag: "--lora",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "lora_scaled",
        flag: "--lora-scaled",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "alias",
        flag: "--alias",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "tags",
        flag: "--tags",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "api_key",
        flag: "--api-key",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "api_key_file",
        flag: "--api-key-file",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "ssl_key_file",
        flag: "--ssl-key-file",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "ssl_cert_file",
        flag: "--ssl-cert-file",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "api_prefix",
        flag: "--api-prefix",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "path",
        flag: "--path",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "ui_config",
        flag: "--ui-config",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "ui_config_file",
        flag: "--ui-config-file",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "ui_mcp_proxy",
        flag: "--ui-mcp-proxy",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_ui_mcp_proxy",
        flag: "--no-ui-mcp-proxy",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "tools",
        flag: "--tools",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "agent",
        flag: "--agent",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_agent",
        flag: "--no-agent",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "ui",
        flag: "--ui",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_ui",
        flag: "--no-ui",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "embedding",
        flag: "--embedding",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "rerank",
        flag: "--rerank",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "reuse_port",
        flag: "--reuse-port",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "timeout",
        flag: "-to",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "sse_ping_interval",
        flag: "--sse-ping-interval",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "threads_http",
        flag: "--threads-http",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "cache_prompt",
        flag: "--cache-prompt",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_cache_prompt",
        flag: "--no-cache-prompt",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "cache_reuse",
        flag: "--cache-reuse",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "metrics",
        flag: "--metrics",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "props",
        flag: "--props",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "slots",
        flag: "--slots",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_slots",
        flag: "--no-slots",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "slot_save_path",
        flag: "--slot-save-path",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "media_path",
        flag: "--media-path",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "models_dir",
        flag: "--models-dir",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "models_preset",
        flag: "--models-preset",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "models_max",
        flag: "--models-max",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "models_autoload",
        flag: "--models-autoload",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_models_autoload",
        flag: "--no-models-autoload",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "jinja",
        flag: "--jinja",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_jinja",
        flag: "--no-jinja",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "reasoning_format",
        flag: "--reasoning-format",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "reasoning",
        flag: "--reasoning",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "reasoning_budget",
        flag: "--reasoning-budget",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "reasoning_budget_message",
        flag: "--reasoning-budget-message",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "reasoning_preserve",
        flag: "--reasoning-preserve",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_reasoning_preserve",
        flag: "--no-reasoning-preserve",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "chat_template",
        flag: "--chat-template",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "chat_template_file",
        flag: "--chat-template-file",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "chat_template_kwargs",
        flag: "--chat-template-kwargs",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "skip_chat_parsing",
        flag: "--skip-chat-parsing",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_skip_chat_parsing",
        flag: "--no-skip-chat-parsing",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "prefill_assistant",
        flag: "--prefill-assistant",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "no_prefill_assistant",
        flag: "--no-prefill-assistant",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "slot_prompt_similarity",
        flag: "--slot-prompt-similarity",
        ptype: ParamType::Float,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "sleep_idle_seconds",
        flag: "--sleep-idle-seconds",
        ptype: ParamType::Int,
        default: "0",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "log_prompts_dir",
        flag: "--log-prompts-dir",
        ptype: ParamType::Str,
        default: "",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
    ParamSpec {
        key: "offline",
        flag: "--offline",
        ptype: ParamType::Bool,
        default: "false",
        min: None,
        max: None,
        choices: None,
        widget: None,
        enabled_by_default: false,
    },
];

// 供前端渲染用的注册表快照（含类型/默认值/候选项），与 PARAM_REGISTRY 同源。
#[tauri::command]
pub fn get_param_registry() -> &'static [ParamSpec] {
    PARAM_REGISTRY
}
